### ISSUE TITLE
Static allocation of ParameterEnumerationValue

### ISSUE THREAD

**Issue by SpotlightKid** [SpotlightKid/midiomatic#1]
From IRC:

> <falktx> strogon14: your PluginMIDISysFilter::initParameter leaks memory. please use static array instead of allocating memory there

I have to admit, my knowledge of C++ is very rudimentary, so I'm not sure what the correct way to do this is.

@falktx: Any examples of the correct usage I could look at?

**Comment by falkTX** [comment]
sorry, I need to make this more clear, yeah.
I even thought we had to not allocate memory there, but I was mistaken as DPF does free memory at some point.
I will get this sorted out at some point..

**Comment by SpotlightKid** [comment]
No worries, I got help on IRC. I suspected that DPF frees the pointer somewhere, but couldn't find the place in the code.
